# Generated by Django 4.1.2 on 2022-11-30 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("to_do", "0002_task"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["status", "create"]},
        ),
        migrations.RenameField(
            model_name="task",
            old_name="done_or_not",
            new_name="status",
        ),
    ]
