# Generated by Django 4.1.2 on 2022-11-30 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("to_do", "0003_alter_task_options_rename_done_or_not_task_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="deadline",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
